//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanogramaGen.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PlanogramaGenEntities : DbContext
    {
        public PlanogramaGenEntities()
            : base("name=PlanogramaGenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_usuarios> tb_usuarios { get; set; }
        public virtual DbSet<ReglasNegocio> ReglasNegocio { get; set; }
        public virtual DbSet<PlanogramaCenefas> PlanogramaCenefas { get; set; }
        public virtual DbSet<PlanogramaObjetos> PlanogramaObjetos { get; set; }
        public virtual DbSet<PlanogramaEncabezado> PlanogramaEncabezado { get; set; }
        public virtual DbSet<PlanogramaProductos> PlanogramaProductos { get; set; }
    
        public virtual ObjectResult<string> sp_validar_usuario(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_validar_usuario", usuarioParameter);
        }
    
        public virtual int sp_eliminar_planograma(Nullable<int> plnid)
        {
            var plnidParameter = plnid.HasValue ?
                new ObjectParameter("plnid", plnid) :
                new ObjectParameter("plnid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_eliminar_planograma", plnidParameter);
        }
    
        public virtual ObjectResult<sp_obtener_categorias_Result> sp_obtener_categorias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_obtener_categorias_Result>("sp_obtener_categorias");
        }
    
        public virtual ObjectResult<sp_arbol_zonificacion_Result> sp_arbol_zonificacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_arbol_zonificacion_Result>("sp_arbol_zonificacion");
        }
    
        public virtual ObjectResult<sp_obtener_segmentos_labels_Result> sp_obtener_segmentos_labels(Nullable<int> pLN_ID)
        {
            var pLN_IDParameter = pLN_ID.HasValue ?
                new ObjectParameter("PLN_ID", pLN_ID) :
                new ObjectParameter("PLN_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_obtener_segmentos_labels_Result>("sp_obtener_segmentos_labels", pLN_IDParameter);
        }
    
        public virtual ObjectResult<sp_obtener_planograma_Result> sp_obtener_planograma(string tienda, string categoria)
        {
            var tiendaParameter = tienda != null ?
                new ObjectParameter("Tienda", tienda) :
                new ObjectParameter("Tienda", typeof(string));
    
            var categoriaParameter = categoria != null ?
                new ObjectParameter("Categoria", categoria) :
                new ObjectParameter("Categoria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_obtener_planograma_Result>("sp_obtener_planograma", tiendaParameter, categoriaParameter);
        }
    }
}
