//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanogramaGen.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanogramaProductos
    {
        public int PLN_ID { get; set; }
        public string PRODUCT_ID { get; set; }
        public string FIXEL_ID { get; set; }
        public string PROD_NAME { get; set; }
        public double X_PROD { get; set; }
        public double Y_PROD { get; set; }
        public double PRODUCT_WIDTH { get; set; }
        public double PRODUCT_WIDTH_REAL { get; set; }
        public double PRODUCT_WIDTH_PIXEL { get; set; }
        public double PRODUCT_HEIGHT { get; set; }
        public double PRODUCT_HEIGHT_PIXEL { get; set; }
        public int ORIENTATION { get; set; }
        public int MERCH_STYLE { get; set; }
        public int VERTICAL { get; set; }
        public int TOTAL_FACINGS { get; set; }
        public int UNITS_CASE_DEEP { get; set; }
    }
}
