//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanogramaGen.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanogramaObjetos
    {
        public int PLN_ID { get; set; }
        public string FIXEL_ID { get; set; }
        public int SEGMENT { get; set; }
        public int TYPE { get; set; }
        public int COLOURISCLEAR { get; set; }
        public int FILL_COLOR { get; set; }
        public int COLOUR { get; set; }
        public Nullable<int> SIZE_VAL { get; set; }
        public string FONT_NAME { get; set; }
        public string LABEL { get; set; }
        public string TEXTFIELD { get; set; }
        public double XPIX { get; set; }
        public double YPIX { get; set; }
        public double WIDTH { get; set; }
        public double WIDTH_PIXEL { get; set; }
        public double HEIGHT { get; set; }
        public double HEIGHT_PIXEL { get; set; }
    }
}
