//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanogramaGen.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanogramaCenefas
    {
        public int PLN_ID { get; set; }
        public string FIXEL_ID { get; set; }
        public double X_CENEFA { get; set; }
        public double Y_CENEFA { get; set; }
        public int COLOUR_CENEFA { get; set; }
        public double SEGMENT_WIDTH { get; set; }
        public double SEGMENT_WIDTH_PIXEL { get; set; }
        public double SEGMENT_HEIGHT { get; set; }
        public double SEGMENT_HEIGHT_PIXEL { get; set; }
        public string LABEL_CENEFA { get; set; }
        public int FIXEL_TYPE { get; set; }
        public int SEGMENT { get; set; }
    }
}
